<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Quot extends Model
{

    protected $table = 'quot';
    protected $primaryKey = 'id';

    protected $fillable = [
        'quot_date',
        'quot_sales',
        'quot_ref',
        'quot_client_id',
        'quot_site_id',
        'quot_jobtype',
        'quot_setqty',
        'quot_periodnum',
        'quot_periodtype',
        'quot_startday',
        'quot_endday',
        'quot_rentdiscount',
        'quot_contractrent',
        'quot_deliverycharge',
        'quot_setupcharge',
        'quot_form5charge',
        'quot_contractdiscount',
        'quot_contractamount',
        'quot_deposit',
        'quot_contactperson',
        'quot_salesname',
        'quot_status',
        'quot_related',
        'quot_comment',
        'quot_remark',
        'quot_displaylang',
        'quot_pagedisplay',
        'quot_archive',
        'quot_deposit_cm',
        'quot_ds',
        'quot_editowner',
        'quot_editowner_name',
        'quot_cs',
        'quot_lnd_status',
        'quot_tdc',
        'quot_type',
        'quot_contactperson_name',
        'quot_site_name',
        'quot_client_name',
        'quot_last_mod_user_name',
        'quot_partssum',
        'quot_validity',
        'quot_paymentmethod',
        'quot_form5credit',
        'quot_flag',
        'quot_last_mod_user',
        'quot_creation_time',
        'quot_last_mod_time',
        'quot_deliveryqty',
        'quot_deliveryfoc',
        'quot_form5info',
        'quot_form5period',
        'quot_form5qty',
        'quot_form5setqty',
        'quot_form5extra',
        'quot_salesfocform5',
        'quot_deliverytime',
        'quot_starttime',
        'quot_endtime',
        'quot_deliveryneedlabor',
        'quot_deliverywithworker',
        'quot_confirmdate',
        'quot_confirminfo',
        'quot_laborsignform5',
        'quot_laborsignquot',
        'quot_ad',
        'quot_assemblyqty',
        'quot_disassemblyqty',
        'quot_daycpqty',
        'quot_daydriverqty',
        'quot_nightcpqty',
        'quot_nightdriverqty',
        'quot_nightshiplabor',
        'quot_nightshiponly',
        'quot_bankcheckdeposit',
        'quot_bankcheckitem',
        'quot_paymentfirst',
        'quot_receipt',
        'quot_depositback',
        'quot_paymentat',
        'quot_setmarking',
        'quot_setcolor',
        'quot_paymentmonthly',
        'quot_paymentdelivery',
        'quot_paymentassembly',
        'quot_confirmation'
    ];
}
