# ./docker-compose.yml

version: '3'

services:
  demo-quotation-web:
    # image: mattrayner/lamp:latest-1604-php7
    build: ./laravel-php7
    container_name: demo-quotation-web
    volumes:
      - ../app/:/app
    ports:
      - "8002:80"

    restart: always
    networks:
        - proxy
    labels:
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"
        - "traefik.basic.frontend.rule=Host:temp.louislabs.com"
        - "traefik.basic.port=80"
        - "traefik.basic.protocol=http"

networks:
  proxy:
    external: true
